apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-deploy
  template:
    metadata:
      labels:
        app: gke-deploy
    spec:
      containers:
        - name: confluent-deployment
          image: us-central1-docker.pkg.dev/confluent-kafka-app/sm-deployments/gke-deploy:0.1.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/config
              name: confluent-vars
      serviceAccountName: kube-deployment-account
      terminationGracePeriodSeconds: 30
      volumes:
        - name: confluent-vars
          csi:
            driver: secrets-store-gke.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: confluent-credentials