# Kafka Setting to Access Confluent Topics
spring:
  application:
    name: gke-deploy
  config:
    import: configtree:/var/config/
  kafka:
    bootstrap-servers: pkc-q8pdd.us-east4.gcp.confluent.cloud:9092
    consumer:
      group-id: local-22-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 120000
        request.timeout.ms: 120000
    properties:
      session.timeout.ms: 45000
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${CONFLUENT-USERNAME}' password='${CONFLUENT-PASSWORD}';
